const products = [
  {
    id: 0,
    name: "Apple Watch 7",
    price: 399,
    instock: 100,
    imgSrc: "images/product_img/apple-watch.jpg",
  },
  {
    id: 1,
    name: "Ipad Pro 12inch",
    price: 799,
    instock: 100,
    imgSrc: "images/product_img/ipad-pro.jpg",
  },
  {
    id: 2,
    name: "Iphone 11",
    price: 699,
    instock: 100,
    imgSrc: "images/product_img/iphone11.jpg",
  },
  {
    id: 3,
    name: "Google Pixel 4",
    price: 699,
    instock: 100,
    imgSrc: "images/product_img/pixel4.jpg",
    numberOfItems: 1,
  },
  {
    id: 4,
    name: "Google Pixel 4a",
    price: 349,
    instock: 100,
    imgSrc: "images/product_img/pixel4a.jpg",
  },
  {
    id: 5,
    name: "Poco M4",
    price: 199,
    instock: 100,
    imgSrc: "images/product_img/poco.jpg",
  },
  {
    id: 6,
    name: "Samsung Galaxy S21 Ultra",
    price: 1199,
    instock: 100,
    imgSrc: "images/product_img/s21ultra.jpg",
  },
  {
    id: 7,
    name: "Xiaomi 11 Ultra",
    price: 999,
    instock: 100,
    imgSrc: "images/product_img/xiaomi1.jpg",
  },
];
